In [1]:
import json
import pandas as pd
lista = [json.loads(line) for line in open('large_eve.json', 'r', encoding='utf-8')]

In [2]:
df = pd.json_normalize(lista)

In [3]:
df.shape[0]

746909

In [4]:
rslt_df = df[(df['event_type'] == "dns") | (df['event_type'] == "DNS")]

In [5]:
rslt_df

,timestamp,flow_id,pcap_cnt,event_type,vlan,src_ip,src_port,dest_ip,dest_port,proto,...,stats.flow_mgr.rows_busy,stats.flow_mgr.rows_maxlen,stats.file_store.open_files,stats.dns.memuse,stats.dns.memcap_state,stats.dns.memcap_global,stats.http.memuse,stats.http.memcap,tcp.ecn,tcp.cwr
2,2017-07-22T17:33:16.661646-0500,1.327836e+15,22269.0,dns,110.0,2001:0dbb:0c18:0011:0260:6eff:fe30:0863,59680.0,2001:0500:0001:0000:0000:0000:803f:0235,53.0,UDP,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,2017-07-22T17:33:24.990320-0500,2.022925e+15,54352.0,dns,110.0,2001:0dbb:0c18:0011:0260:6eff:fe30:0863,38051.0,2001:0500:0003:0000:0000:0000:0000:0042,53.0,UDP,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,2017-07-22T17:33:27.379891-0500,5.785448e+14,54519.0,dns,150.0,192.168.205.170,31393.0,192.168.207.4,53.0,UDP,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,2017-07-22T17:33:27.380146-0500,5.785448e+14,54520.0,dns,150.0,192.168.207.4,53.0,192.168.205.170,31393.0,UDP,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,2017-07-22T17:33:27.380146-0500,5.785448e+14,54520.0,dns,150.0,192.168.207.4,53.0,192.168.205.170,31393.0,UDP,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
716752,2017-07-22T19:47:03.373435-0500,8.918761e+14,4441474.0,dns,120.0,192.168.207.4,53.0,192.168.202.172,60654.0,UDP,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
716753,2017-07-22T19:47:03.373435-0500,8.918761e+14,4441474.0,dns,120.0,192.168.207.4,53.0,192.168.202.172,60654.0,UDP,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
716893,2017-07-22T19:47:38.146503-0500,2.199316e+15,4452917.0,dns,130.0,192.168.203.67,50975.0,192.168.207.4,53.0,UDP,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
716894,2017-07-22T19:47:38.146953-0500,2.199316e+15,4452918.0,dns,130.0,192.168.207.4,53.0,192.168.203.67,50975.0,UDP,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
716895,2017-07-22T19:47:38.146953-0500,2.199316e+15,4452918.0,dns,130.0,192.168.207.4,53.0,192.168.203.67,50975.0,UDP,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
rslt_df.shape[0]

15749

In [7]:
rslt_df.head()

,timestamp,flow_id,pcap_cnt,event_type,vlan,src_ip,src_port,dest_ip,dest_port,proto,...,stats.flow_mgr.rows_busy,stats.flow_mgr.rows_maxlen,stats.file_store.open_files,stats.dns.memuse,stats.dns.memcap_state,stats.dns.memcap_global,stats.http.memuse,stats.http.memcap,tcp.ecn,tcp.cwr
2,2017-07-22T17:33:16.661646-0500,1.327836e+15,22269.0,dns,110.0,2001:0dbb:0c18:0011:0260:6eff:fe30:0863,59680.0,2001:0500:0001:0000:0000:0000:803f:0235,53.0,UDP,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,2017-07-22T17:33:24.990320-0500,2.022925e+15,54352.0,dns,110.0,2001:0dbb:0c18:0011:0260:6eff:fe30:0863,38051.0,2001:0500:0003:0000:0000:0000:0000:0042,53.0,UDP,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,2017-07-22T17:33:27.379891-0500,5.785448e+14,54519.0,dns,150.0,192.168.205.170,31393.0,192.168.207.4,53.0,UDP,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,2017-07-22T17:33:27.380146-0500,5.785448e+14,54520.0,dns,150.0,192.168.207.4,53.0,192.168.205.170,31393.0,UDP,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,2017-07-22T17:33:27.380146-0500,5.785448e+14,54520.0,dns,150.0,192.168.207.4,53.0,192.168.205.170,31393.0,UDP,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
""" rslt_df[rslt_df['dns'].str.contains('"rrtype":"A"')] """
rslt_df = rslt_df[rslt_df['dns.rrtype']==('A')][['dns.rrname','dns.rrtype']]
rslt_df

                                         dns.rrname dns.rrtype
2                              api.wunderground.com          A
38                              stork79.dropbox.com          A
39       hpca-tier2.office.aol.com.ad.aol.aoltw.net          A
43                             api.wunderground.com          A
44             safebrowsing.clients.google.com.home          A
...                                             ...        ...
714913  secure.informaction.com.hsd1.pa.comcast.net          A
715127               192.168.22.201:.stayonline.net          A
715804                           wpad.aol.aoltw.net          A
715910                     client-software.real.com          A
716751                     en-us.start3.mozilla.com          A

[2849 rows x 2 columns]

In [9]:
rslt_df = rslt_df.drop_duplicates(subset=["dns.rrname"])

In [10]:
rslt_df

                                        dns.rrname dns.rrtype
2                             api.wunderground.com          A
38                             stork79.dropbox.com          A
39      hpca-tier2.office.aol.com.ad.aol.aoltw.net          A
44            safebrowsing.clients.google.com.home          A
48                             fxfeeds.mozilla.com          A
...                                            ...        ...
709658                  ntp.ubuntu.com.localdomain          A
711379            redir.metaservices.microsoft.com          A
714198                           ocsp.verisign.com          A
715127              192.168.22.201:.stayonline.net          A
715910                    client-software.real.com          A

[177 rows x 2 columns]

In [11]:
from flare.data_science.features import domain_tld_extract
rslt_df["domain_tld"]= rslt_df["dns.rrname"].apply(lambda x: domain_tld_extract(x))
rslt_df

C:\Users\Sebastian\AppData\Local\Temp\ipykernel_6396\1464007581.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  rslt_df["domain_tld"]= rslt_df["dns.rrname"].apply(lambda x: domain_tld_extract(x))

,dns.rrname,dns.rrtype,domain_tld
2,api.wunderground.com,A,wunderground.com
38,stork79.dropbox.com,A,dropbox.com
39,hpca-tier2.office.aol.com.ad.aol.aoltw.net,A,aoltw.net
44,safebrowsing.clients.google.com.home,A,safebrowsing.clients.google.com.home
48,fxfeeds.mozilla.com,A,mozilla.com
...,...,...,...
709658,ntp.ubuntu.com.localdomain,A,ntp.ubuntu.com.localdomain
711379,redir.metaservices.microsoft.com,A,microsoft.com
714198,ocsp.verisign.com,A,verisign.com
715127,192.168.22.201:.stayonline.net,A,192.168.22.201:.stayonline.net
715910,client-software.real.com,A,real.com

In [12]:
rslt_df = rslt_df[rslt_df.domain_tld != "''"]
rslt_df = rslt_df[rslt_df["dns.rrname"] != "192.168.22.110phpmyadmin"]
rslt_df = rslt_df[rslt_df["dns.rrname"] != "192.168.22.110phpmyadmin.localdomain"]
rslt_df = rslt_df[rslt_df["dns.rrname"] != '"192.168.206.56"']
rslt_df = rslt_df[rslt_df["dns.rrname"] != "192.168.26-27.0"]
rslt_df = rslt_df[rslt_df["dns.rrname"] != "192.168.21.1201"]
rslt_df = rslt_df[rslt_df["dns.rrname"] != "1922.168.22.254"]
rslt_df = rslt_df[rslt_df["dns.rrname"] != "1922.168.22.254.home"]
slt_df = rslt_df[rslt_df["dns.rrname"] != "192.168.21-28.0.home"]
slt_df = rslt_df[rslt_df["dns.rrname"] != "192.168.22.201:"]
slt_df = rslt_df[rslt_df["dns.rrname"] != "192.168.22.201:.stayonline.net"]

In [13]:
rslt_df = rslt_df.drop_duplicates(subset=["domain_tld"])

In [14]:
rslt_df

,dns.rrname,dns.rrtype,domain_tld
2,api.wunderground.com,A,wunderground.com
38,stork79.dropbox.com,A,dropbox.com
39,hpca-tier2.office.aol.com.ad.aol.aoltw.net,A,aoltw.net
44,safebrowsing.clients.google.com.home,A,safebrowsing.clients.google.com.home
48,fxfeeds.mozilla.com,A,mozilla.com
...,...,...,...
701884,192.168.22.201:,A,192.168.22.201:
709658,ntp.ubuntu.com.localdomain,A,ntp.ubuntu.com.localdomain
714198,ocsp.verisign.com,A,verisign.com
715127,192.168.22.201:.stayonline.net,A,192.168.22.201:.stayonline.net
715910,client-software.real.com,A,real.com

In [23]:
filter_df = rslt_df[["domain_tld"]]
filter_df

                                  domain_tld
2                           wunderground.com
38                               dropbox.com
39                                 aoltw.net
44      safebrowsing.clients.google.com.home
48                               mozilla.com
...                                      ...
701884                       192.168.22.201:
709658            ntp.ubuntu.com.localdomain
714198                          verisign.com
715127        192.168.22.201:.stayonline.net
715910                              real.com

[106 rows x 1 columns]

In [24]:
from clasificador import clasificacion
clas_df = clasificacion(filter_df)
clas_df

d:\Program Files\Clases\SEMESTRE8\REDES\LAB9\clasificador.py:114: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['length'] = df['domain_tld'].str.len()
d:\Program Files\Clases\SEMESTRE8\REDES\LAB9\clasificador.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['digits'] = df['domain_tld'].str.count('[0-9]')
d:\Program Files\Clases\SEMESTRE8\REDES\LAB9\clasificador.py:116: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['entropy'] = df['domain_tld'].apply(H_entropy)
d:\Program Files\Clases\SEMESTRE8\REDES\LAB9\clasificador.py:117: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['vowel-cons'] = df['domain_tld'].apply(vowel_consonant_ratio)
d:\Program Files\Clases\SEMESTRE8\REDES\LAB9\clasificador.py:118: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['firstDigitIndex'] = df['domain_tld'].apply(firstDigitIndex)
d:\Program Files\Clases\SEMESTRE8\REDES\LAB9\clasificador.py:123: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['ngrams'] = df['domain_tld'].apply(lambda x: average_ngram_feature([ngram_feature(x, d, 1),
d:\Program Files\Python310\lib\site-packages\sklearn\base.py:310: UserWarning: Trying to unpickle estimator DecisionTreeClassifier from version 1.0.2 when using version 0.24.2. This might lead to breaking code or invalid results. Use at your own risk.
  warnings.warn(

                                  domain_tld  isDGA
2                           wunderground.com      0
38                               dropbox.com      1
39                                 aoltw.net      1
44      safebrowsing.clients.google.com.home      0
48                               mozilla.com      0
...                                      ...    ...
701884                       192.168.22.201:      1
709658            ntp.ubuntu.com.localdomain      1
714198                          verisign.com      0
715127        192.168.22.201:.stayonline.net      1
715910                              real.com      1

[106 rows x 2 columns]

In [25]:
clas_df = clas_df[clas_df["isDGA"] == 1]
clas_df

                            domain_tld  isDGA
38                         dropbox.com      1
39                           aoltw.net      1
53                      metasploit.com      1
3266                       windows.com      1
5071                     ntkrnlpa.info      1
7546                    sql-ledger.org      1
8104               backtrack-linux.org      1
13241                   phpmyadmin.net      1
23995                    microsoft.com      1
36126                   postgresql.org      1
43948                      freepbx.org      1
45179                bigflickrfeed.com      1
58278                       flickr.com      1
65558                  malwarecity.com      1
74253                     facebook.com      1
110417                      xmarks.com      1
113610                     cakephp.org      1
119193                       adams.net      1
119201                    clarkson.edu      1
119214                       ecvps.com      1
119226                        wisc.edu      1
119253                    easynews.com      1
119255                    bluehost.com      1
119310                      kernel.org      1
119339                   liquidweb.com      1
119616                  team-cymru.org      1
119693                    xmission.com      1
131970                       apple.com      1
206092                    msftncsi.com      1
339172            vtlfccmfxlkgifuf.com      1
363172                  macromates.com      1
449992                 192.168.21-28.0      1
452490            ejfodfmfxlkgifuf.xyz      1
485820            192.168.21-28.0.home      1
701884                 192.168.22.201:      1
709658      ntp.ubuntu.com.localdomain      1
715127  192.168.22.201:.stayonline.net      1
715910                        real.com      1